import Foundation
import XCTest
#if canImport(KabbaSyncCore)
@testable import KabbaSyncCore
#endif

/// Phase 4 shared fixtures (RentnKingTests/KabbaSyncCore/Fixtures/*.json — generated by the
/// Laravel suite, copied by Scripts/sync-contract-fixtures.sh): the Swift side decodes the
/// SAME JSON Laravel asserts the API produces.
final class Phase4ContractTests: XCTestCase {

    private func fixture(_ name: String) throws -> Data {
        let candidates = [
            URL(fileURLWithPath: #filePath).deletingLastPathComponent().appendingPathComponent("Fixtures/\(name).json"),
            Bundle(for: Phase4ContractTests.self).url(forResource: name, withExtension: "json"),
        ].compactMap { $0 }
        for url in candidates where FileManager.default.fileExists(atPath: url.path) {
            return try Data(contentsOf: url)
        }
        throw XCTSkip("Fixture \(name).json not synced — run Scripts/sync-contract-fixtures.sh")
    }

    func testBoardItemCarriesExplicitIdentityChecklistStateAndInTransit() throws {
        let item = try QueueLineItemContract.decode(fixture("queue_line_board_item"))
        XCTAssertEqual(item.identity.orderProductUniqueId, item.orderProductUniqueId)
        XCTAssertEqual(item.identity.queueLineItemId, item.orderProductUniqueId, "the Queue Line item IS the order product")
        XCTAssertEqual(item.identity.orderUniqueId, item.orderUniqueId)
        XCTAssertEqual(item.identity.fulfillmentLeg, "delivery")
        XCTAssertEqual(item.identity.leg, .delivery)
        XCTAssertEqual(item.identity.equipmentUniqueId, item.equipment?.uniqueId)
        XCTAssertNotNil(item.identity.equipmentUniqueId)
        XCTAssertEqual(item.checklist.delivery.status, .notPrepared)
        XCTAssertEqual(item.checklist.delivery.leg, "delivery")
        XCTAssertEqual(item.status, "pending")
        // Checklist-driven staging (2026-09): the derived dispatch flag is on
        // every item; a fresh pending item is not traveling anywhere.
        XCTAssertFalse(item.inTransit)
        XCTAssertFalse(item.staged)
    }

    // (The mark-staged acknowledgment/conflict fixtures were retired with the
    //  queue_line.mark_staged operation — staging is the Delivery Checklist's
    //  Save, covered by the checklist prepare contract + QueueLineOperationTests.)

    func testMediaUploadSuccessAndReplayAreAcknowledgments() throws {
        let success = try fixture("media_upload_success")
        let outcome = SyncResponseInterpreter.interpret(SyncHTTPResponse(statusCode: 200, headers: [:], body: success), now: Date())
        guard case .acknowledged(let ack) = outcome else { return XCTFail("expected acknowledgment") }
        XCTAssertEqual(ack.data?["client_media_id"]?.stringValue, "fixture-client-media-0001")
        XCTAssertEqual(ack.data?["type"]?.stringValue, "delivery")
        XCTAssertEqual(ack.data?["leg"]?.stringValue, "delivery")
        XCTAssertNotNil(ack.data?["order_product_unique_id"]?.stringValue)
        XCTAssertNotNil(ack.data?["checklist_execution_id"]?.stringValue)
        XCTAssertEqual(ack.data?["already_uploaded"]?.boolValue, false)
        XCTAssertFalse(ack.replayed)

        let replay = try fixture("media_upload_idempotent_replay")
        let replayOutcome = SyncResponseInterpreter.interpret(SyncHTTPResponse(statusCode: 200, headers: ["X-Idempotent-Replay": "true"], body: replay), now: Date())
        guard case .acknowledged(let r) = replayOutcome else { return XCTFail("expected acknowledgment") }
        XCTAssertTrue(r.replayed)
        XCTAssertEqual(r.data?["order_media_unique_id"]?.stringValue, ack.data?["order_media_unique_id"]?.stringValue, "one record for two submissions")
    }

    func testMediaClientIdConflictIsPermanentAndNamesTheExistingAssociation() throws {
        let data = try fixture("media_client_id_conflict")
        let outcome = SyncResponseInterpreter.interpret(SyncHTTPResponse(statusCode: 409, headers: [:], body: data), now: Date())
        guard case .failed(let error) = outcome else { return XCTFail("expected failure") }
        XCTAssertEqual(error.code, "MEDIA_CLIENT_ID_CONFLICT")
        XCTAssertEqual(error.disposition, .needsAttention)
        XCTAssertNotNil(APIEnvelope.parse(data)?.data?["existing_order_product_unique_id"]?.stringValue)
    }
}
