import Foundation
import XCTest
#if canImport(KabbaSyncCore)
@testable import KabbaSyncCore
#endif

/// Phase 5 shared fixtures (generated by the Laravel suite, copied by Scripts/sync-contract-fixtures.sh):
/// the Swift side reads the SAME JSON Laravel asserts it produces for login, 401, 426, 410 and app/release.
final class Phase5ContractTests: XCTestCase {

    private func fixture(_ name: String) throws -> Data {
        let candidates = [
            URL(fileURLWithPath: #filePath).deletingLastPathComponent().appendingPathComponent("Fixtures/\(name).json"),
            Bundle(for: Phase5ContractTests.self).url(forResource: name, withExtension: "json"),
        ].compactMap { $0 }
        for url in candidates where FileManager.default.fileExists(atPath: url.path) {
            return try Data(contentsOf: url)
        }
        throw XCTSkip("Fixture \(name).json not synced — run Scripts/sync-contract-fixtures.sh")
    }

    func testLoginProducesAPerInstallSessionRecordAndAReleaseBlock() throws {
        let data = try fixture("auth_login_success")
        let record = try XCTUnwrap(SessionRecord.decode(loginResponse: data))
        XCTAssertEqual(record.scope, "installation")
        XCTAssertNotNil(record.installationId)
        XCTAssertNotNil(record.expiresAt, "identified installs get a sliding expiry")
        XCTAssertEqual(record.slidingTTLDays, 30)
        XCTAssertEqual(record.appBuild, "1001")
        let release = try XCTUnwrap(ReleasePolicy.decode(envelopeData: data))
        XCTAssertEqual(release.state, "no_policy")
        XCTAssertFalse(release.updateRequired)
        // The legacy keys the deployed client parses are still there.
        let root = try XCTUnwrap(JSONValue.parse(data))
        XCTAssertEqual(root["success"]?.boolValue, true)
        XCTAssertNotNil(root["user"]?["token"]?.stringValue)
        XCTAssertNotNil(root["request_id"]?.stringValue)
    }

    func testAnExpiredSessionIsA401ThatPausesForAuthentication() throws {
        let data = try fixture("auth_unauthenticated_expired")
        let outcome = SyncResponseInterpreter.interpret(SyncHTTPResponse(statusCode: 401, headers: [:], body: data), now: Date())
        guard case .failed(let error) = outcome else { return XCTFail("expected failure") }
        XCTAssertEqual(error.code, "UNAUTHENTICATED")
        XCTAssertEqual(error.disposition, .waitForAuthentication)
        XCTAssertEqual(error.serverRetryable, false)
        XCTAssertEqual(APIEnvelope.parse(data)?.raw["error"]?["reason"]?.stringValue, "expired")
        XCTAssertEqual(APIEnvelope.parse(data)?.message, "Unauthenticated.", "the key v1.0.17 already reads")
    }

    func testAnUpdateRequiredResponseIsA426ThatPausesForAppUpdateAndCarriesThePolicy() throws {
        let data = try fixture("app_update_required")
        let outcome = SyncResponseInterpreter.interpret(SyncHTTPResponse(statusCode: 426, headers: ["X-Mobile-Update": "required"], body: data), now: Date())
        guard case .failed(let error) = outcome else { return XCTFail("expected failure") }
        XCTAssertEqual(error.code, "APP_UPDATE_REQUIRED")
        XCTAssertEqual(error.disposition, .waitForAppUpdate)
        let policy = try XCTUnwrap(ReleasePolicy.decode(envelopeData: data))
        XCTAssertTrue(policy.updateRequired)
        XCTAssertEqual(policy.minimumSupportedBuild, "1001")
        XCTAssertEqual(policy.recommendedBuild, "1002")
        XCTAssertNotNil(policy.storeURL)
        XCTAssertTrue(policy.stillRequiresUpdate(forBuild: "1000"))
        XCTAssertFalse(policy.stillRequiresUpdate(forBuild: "1001"))
        XCTAssertEqual(UpdateAdvice.from(headers: ["X-Mobile-Update": "required"])?.level, .required)
    }

    func testARetiredRouteIsA410ThatNeedsAttentionAndNamesTheReplacement() throws {
        let data = try fixture("route_retired")
        let outcome = SyncResponseInterpreter.interpret(SyncHTTPResponse(statusCode: 410, headers: ["Deprecation": "true"], body: data), now: Date())
        guard case .failed(let error) = outcome else { return XCTFail("expected failure") }
        XCTAssertEqual(error.code, "ROUTE_RETIRED")
        XCTAssertEqual(error.disposition, .needsAttention)
        XCTAssertNotNil(APIEnvelope.parse(data)?.data?["replacement"]?.stringValue)
    }

    func testAppReleaseWithoutAPolicyIsSupportedAndDescribesTheUploadCeiling() throws {
        let data = try fixture("app_release_no_policy")
        let policy = try XCTUnwrap(ReleasePolicy.decode(envelopeData: data))
        XCTAssertEqual(policy.state, "no_policy")
        XCTAssertFalse(policy.updateRequired)
        XCTAssertFalse(policy.updateRecommended)
        let upload = try XCTUnwrap(APIEnvelope.parse(data)?.data?["upload"])
        XCTAssertNotNil(upload["laravel_rule_bytes"]?.stringValue)
        XCTAssertTrue(upload["effective_max_bytes"] != nil, "present even when unlimited (null)")
    }
}
